### ISSUE TITLE
Versioning - Different 3.0 versions made avaiable 

### ISSUE THREAD

**Issue by pedropaulofb** [ontolex/lexinfo#10]
Dear authors,

I am working an Ontolex project using Vocbench. I could note that most of the Lexinfo properties there listed are not defined in Lexinfo 3.0 available at https://www.lexinfo.net/ontology/3.0/lexinfo. 

Considering this, I have sent an email to the Vocbench email group. To view the discussion, please visit https://groups.google.com/d/msgid/vocbench-user/d333e8e9-18de-4eb2-a37a-d0861e3381b6n%40googlegroups.com. 

I got a response from Vocbench developers, who told me that they obtained the Lexinfo definition from the GitHub repository: https://github.com/ontolex/lexinfo/blob/master/ontology/3.0/lexinfo.owl

The issue is that both references of Lexinfo (website and Github) are labeled as version 3.0. In this case, which version should I consider for my project? In addition, for the sake of better referencing for newcomers like me, shouldn’t the versions be using different numbers?

Thank you in advance for your support.

Kind regards, 
Pedro Paulo Favato Barcelos.

**Comment by jmccrae** [comment]
Thanks for the report I have updated the lexinfo.net site
