### ISSUE TITLE
Missing comma in relations.csv

### ISSUE THREAD

**Issue by rwingerter55** [ontolex/lexinfo#14]
Looking at Fix #12 I noticed that a comma is missing in line 6 of relations.csv. 

> approximateSynonym,,LexicalSense,Y,N,

should be

> approximateSynonym,,LexicalSense,,Y,N,

**Comment by jmccrae** [comment]
Fixed by https://github.com/ontolex/lexinfo/commit/046cbecd42d83b4fd0c75a00fa856a2c98a33f2f
