### ISSUE TITLE
Error in labels of subclasses of <http://www.w3.org/ns/lemon/ontolex#Affix>

### ISSUE THREAD

**Issue by dlindem** [ontolex/lexinfo#15]
All subclasses of <http://www.w3.org/ns/lemon/ontolex#Affix> in 3.0 have the same rdfs:label "infix", while the label should be "infix", "prefix", "suffix". 
The affected are:
<http://www.lexinfo.net/ontology/3.0/lexinfo#Suffix>, <http://www.lexinfo.net/ontology/3.0/lexinfo#Prefix>.
The same is happening with subclasses of <http://www.w3.org/ns/lemon/ontolex#MultiwordExpression> ("Noun Phrase", "Adjective Phrase", etc.)

**Comment by dlindem** [comment]
Another issue is that <http://www.w3.org/ns/lemon/ontolex#MultiWordExpression> (just once) and <http://www.w3.org/ns/lemon/ontolex#MultiwordExpression> (4 times) both appear in 3.0; should be the same, I think.

**Comment by jmccrae** [comment]
Thanks for the report!
