### ISSUE TITLE
http://www.lexinfo.net/ontology/3.0/lexinfo is unavailable

### ISSUE THREAD

**Issue by pedropaulofb** [ontolex/lexinfo#19]
http://www.lexinfo.net/ontology/3.0/lexinfo is unavailable ("This site can’t be reached", ERR_CONNECTION_TIMED_OUT). Because of this, it is not possible to directly load Lexinfo from the web and also solve missing imports in editors.

**Comment by jmccrae** [comment]
Sorry, for not responding to this promptly. This was due to a cyber attack on our networks.

**Comment by pedropaulofb** [comment]
Hi! Don't worry. I noticed that the page is back to normal, so I closed the
issue. =)

Kind regards - Cordiali saluti - Atenciosamente,
Pedro Paulo Favato Barcelos


Em qui., 18 de nov. de 2021 às 14:39, John McCrae ***@***.***>
escreveu:
