### ISSUE TITLE
provide correct mediatype for https://lexinfo.net/ontology/3.0/lexinfo

### ISSUE THREAD

**Issue by chiarcos** [ontolex/lexinfo#20]
In Apache Jena, the following query fails:

    PREFIX lexinfo: <http://www.lexinfo.net/ontology/3.0/lexinfo#>
    SELECT *
    FROM <https://lexinfo.net/ontology/3.0/lexinfo>
    WHERE {
     ?a a lexinfo:TermElement
    }

error `Failed to determine the content type: (URI=https://lexinfo.net/ontology/3.0/lexinfo : stream=null)`

(test with [sparql.org](http://sparql.org/sparql?query=PREFIX+lexinfo%3A+%3Chttp%3A%2F%2Fwww.lexinfo.net%2Fontology%2F3.0%2Flexinfo%23%3E%0D%0ASELECT+*%0D%0AFROM+%3Chttps%3A%2F%2Flexinfo.net%2Fontology%2F3.0%2Flexinfo%3E%0D%0AWHERE+%7B%0D%0A+%3Fa+a+lexinfo%3ATermElement%0D%0A%7D&default-graph-uri=&output=xml&stylesheet=%2Fxml-to-html.xsl))

This is because the file type is not included in the URI (and it shouldn't be) and the SPARQL engine requests an RDF media type, but the server doesn't implement content negotiation. With file type in URI, the fall-back heuristics would work, but otherwise not.

**Comment by jmccrae** [comment]
Transferred to https://github.com/jmccrae/lexinfo.net/issues/2
