### ISSUE TITLE
sync TTL and RDF editions of lexinfo

### ISSUE THREAD

**Issue by chiarcos** [ontolex/lexinfo#25]
Apparently, https://lexinfo.net/ontology/3.0/lexinfo and https://lexinfo.net/ontology/3.0/lexinfo.ttl are not identical.
I found this by chance with the following query:
    
    PREFIX lexinfo: <http://www.lexinfo.net/ontology/3.0/lexinfo#>
    PREFIX ontolex: <http://www.w3.org/ns/lemon/ontolex#>
    PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
    SELECT *
    FROM <https://lexinfo.net/ontology/3.0/lexinfo.ttl>
    WHERE {  ?b rdfs:subPropertyOf ontolex:usage}

This query (which, BTW, Apache Jena cannot execute over https://lexinfo.net/ontology/3.0/lexinfo because it is not able to guess the correct mediatype, try with http://sparql.org/sparql.html) does not retrieve `lexinfo:domain`, whereas the RDF/XML edition under https://lexinfo.net/ontology/3.0/lexinfo it is defined as a subproperty of `ontolex:usage`.

**Comment by jmccrae** [comment]
Updated
